#ifndef PALTFORMPEPENDENTSERVICES_H_INCLUDED
#define PALTFORMPEPENDENTSERVICES_H_INCLUDED

#include "Arduino.h"
#include "stdint.h"
#include "SoftwareSerial.h"

#endif // PALTFORMPEPENDENTSERVICES_H_INCLUDED
